long __stdcall AbortSystemShutdownA(char* lpMachineName);
long __stdcall AreAllAccessesGranted(long GrantedAccess, long DesiredAccess);
long __stdcall AreAnyAccessesGranted(long GrantedAccess, long DesiredAccess);
long __stdcall BackupEventLogA(long hEventLog, char* lpBackupFileName);
long __stdcall ChangeServiceConfigA(long hService, long dwServiceType, long dwStartType, long dwErrorControl, char* lpBinaryPathName, char* lpLoadOrderGroup, long* lpdwTagId, char* lpDependencies, char* lpServiceStartName, char* lpPassword, char* lpDisplayName);
long __stdcall ClearEventLogA(long hEventLog, char* lpBackupFileName);
long __stdcall CloseEventLog(long hEventLog);
long __stdcall CloseServiceHandle(long hSCObject);
long __stdcall CreateServiceA(long hSCManager, char* lpServiceName, char* lpDisplayName, long dwDesiredAccess, long dwServiceType, long dwStartType, long dwErrorControl, char* lpBinaryPathName, char* lpLoadOrderGroup, long* lpdwTagId, char* lpDependencies, char* lp, char* lpPassword);
long __stdcall DeleteService(long hService);
long __stdcall DeregisterEventSource(long hEventLog);
long __stdcall DuplicateToken(long ExistingTokenHandle, short* ImpersonationLevel, long* DuplicateTokenHandle);
long __stdcall GetNumberOfEventLogRecords(long hEventLog, long* NumberOfRecords);
long __stdcall GetOldestEventLogRecord(long hEventLog, long* OldestRecord);
long __stdcall GetServiceDisplayNameA(long hSCManager, char* lpServiceName, char* lpDisplayName, long* lpcchBuffer);
long __stdcall GetServiceKeyNameA(long hSCManager, char* lpDisplayName, char* lpServiceName, long* lpcchBuffer);
long __stdcall GetUserNameA(char* lpBuffer, long* nSize);
long __stdcall ImpersonateNamedPipeClient(long hNamedPipe);
long __stdcall ImpersonateSelf(short* ImpersonationLevel);
long __stdcall InitiateSystemShutdownA(char* lpMachineName, char* lpMessage, long dwTimeout, long bForceAppsClosed, long bRebootAfterShutdown);
long __stdcall LockServiceDatabase(long hSCManager);
long __stdcall LookupAccountNameA(char* lpSystemName, char* lpAccountName, long* Sid, long* cbSid, char* ReferencedDomainName, long* cbReferencedDomainName, short* peUse);
long __stdcall LookupPrivilegeDisplayNameA(char* lpSystemName, char* lpName, char* lpDisplayName, long* cbDisplayName, long* lpLanguageID);
long __stdcall NotifyBootConfigStatus(long BootAcceptable);
long __stdcall NotifyChangeEventLog(long hEventLog, long hEvent);
long __stdcall OpenBackupEventLogA(char* lpUNCServerName, char* lpFileName);
long __stdcall OpenEventLogA(char* lpUNCServerName, char* lpSourceName);
long __stdcall OpenProcessToken(long ProcessHandle, long DesiredAccess, long* TokenHandle);
long __stdcall OpenSCManagerA(char* lpMachineName, char* lpDatabaseName, long dwDesiredAccess);
long __stdcall OpenServiceA(long hSCManager, char* lpServiceName, long dwDesiredAccess);
long __stdcall OpenThreadToken(long ThreadHandle, long DesiredAccess, long OpenAsSelf, long* TokenHandle);
long __stdcall RegCloseKey(long hKey);
long __stdcall RegConnectRegistryA(char* lpMachineName, long hKey, long* phkResult);
long __stdcall RegCreateKeyA(long hKey, char* lpSubKey, long* phkResult);
long __stdcall RegDeleteKeyA(long hKey, char* lpSubKey);
long __stdcall RegDeleteValueA(long hKey, char* lpValueName);
long __stdcall RegEnumKeyA(long hKey, long dwIndex, char* lpName, long cbName);
long __stdcall RegFlushKey(long hKey);
long __stdcall RegLoadKeyA(long hKey, char* lpSubKey, char* lpFile);
long __stdcall RegNotifyChangeKeyValue(long hKey, long bWatchSubtree, long dwNotifyFilter, long hEvent, long fAsynchronus);
long __stdcall RegOpenKeyA(long hKey, char* lpSubKey, long* phkResult);
long __stdcall RegOpenKeyExA(long hKey, char* lpSubKey, long ulOptions, long samDesired, long* phkResult);
long __stdcall RegQueryValueA(long hKey, char* lpSubKey, char* lpValue, long* lpcbValue);
long __stdcall RegQueryValueExA(long hKey, char* lpValueName, long mustBeZero, long* lpType, char* lpData, long* lpcbData);
long __stdcall RegReplaceKeyA(long hKey, char* lpSubKey, char* lpNewFile, char* lpOldFile);
long __stdcall RegRestoreKeyA(long hKey, char* lpFile, long dwFlags);
long __stdcall RegSetValueA(long hKey, char* lpSubKey, long dwType, char* lpData, long cbData);
long __stdcall RegUnLoadKeyA(long hKey, char* lpSubKey);
long __stdcall RegisterEventSourceA(char* lpUNCServerName, char* lpSourceName);
long __stdcall RegisterServiceCtrlHandlerA(char* lpServiceName, long lpHandlerProc);
long __stdcall RevertToSelf(void);
long __stdcall SetServiceBits(long hServiceStatus, long dwServiceBits, short bSetBitsOn, short bUpdateImmediately);
long __stdcall SetThreadToken(long* Thread, long Token);
long __stdcall StartServiceA(long hService, long dwNumServiceArgs, long lpServiceArgVectors);
