
char* __stdcall CharLowerA(char* lpsz);
char* __stdcall CharNextA(char* lpsz);
char* __stdcall CharPrevA(char* lpszStart, char* lpszCurrent);
char* __stdcall CharUpperA(char* lpsz);
long __stdcall ActivateKeyboardLayout(long HKL, long flags);
long __stdcall AnyPopup(void);
long __stdcall ArrangeIconicWindows(long hwnd);
long __stdcall AttachThreadInput(long idAttach, long idAttachTo, long fAttach);
long __stdcall BeginDeferWindowPos(long nNumWindows);
long __stdcall BringWindowToTop(long hwnd);
long __stdcall BroadcastSystemMessage(long dw, long* pdw, long un, long wParam, long lParam);
long __stdcall CallWindowProcA(long lpPrevWndFunc, long hWnd, long Msg, long wParam, long lParam);
long __stdcall ChangeClipboardChain(long hwnd, long hWndNext);
long __stdcall ChangeMenuA(long hMenu, long cmd, char* lpszNewItem, long cmdInsert, long flags);
long __stdcall CharLowerBuffA(char* lpsz, long cchLength);
long __stdcall CharToOemA(char* lpszSrc, char* lpszDst);
long __stdcall CharToOemBuffA(char* lpszSrc, char* lpszDst, long cchDstLength);
long __stdcall CharUpperBuffA(char* lpsz, long cchLength);
long __stdcall CheckDLGButtonA(long hDlg, long nIDButton, long wCheck);
long __stdcall CheckMenuItem(long hMenu, long wIDCheckItem, long wCheck);
long __stdcall CheckMenuRadioItem(long hMenu, long un1, long un2, long un3, long un4);
long __stdcall CheckRadioButtonA(long hDlg, long nIDFirstButton, long nIDLastButton, long nIDCheckButton);
long __stdcall ChildWindowFromPoint(long hWnd, long xPoint, long yPoint);
long __stdcall CloseClipboard(void);
long __stdcall CloseDesktop(long hDesktop);
long __stdcall CloseWindow(long hwnd);
long __stdcall CloseWindowStation(long hWinSta);
long __stdcall CopyCursor(long hcur);
long __stdcall CopyIcon(long hIcon);
long __stdcall CopyImage(long handle, long un1, long n1, long n2, long un2);
long __stdcall CountClipboardFormats(void);
long __stdcall CreateCaret(long hwnd, long hBitmap, long nWidth, long nHeight);
long __stdcall CreateDialogParamA(long hInstance, char* lpName, long hWndParent, long lpDialogFunc, long lParamInit);
long __stdcall CreateMDIWindowA(char* lpClassName, char* lpWindowName, long dwStyle, long x, long y, long nWidth, long nHeight, long hWndParent, long hInstance, long lParam);
long __stdcall CreateMenu(void);
long __stdcall CreatePopupMenu(void);
long __stdcall DdeAbandonTransaction(long idInst, long hConv, long idTransaction);
long __stdcall DdeAccessDataA(long hData, long* pcbDataSize);
long __stdcall DdeCmpStringHandles(long hsz1, long hsz2);
long __stdcall DdeCreateStringHandleA(long idInst, char* psz, long iCodePage);
long __stdcall DdeDisconnect(long hConv);
long __stdcall DdeDisconnectList(long hConvList);
long __stdcall DdeEnableCallback(long idInst, long hConv, long wCmd);
long __stdcall DdeFreeDataHandle(long hData);
long __stdcall DdeFreeStringHandle(long idInst, long hsz);
long __stdcall DdeGetLastError(long idInst);
long __stdcall DdeImpersonateClient(long hConv);
long __stdcall DdeKeepStringHandle(long idInst, long hsz);
long __stdcall DdeNameService(long idInst, long hsz1, long hsz2, long afCmd);
long __stdcall DdePostAdvise(long idInst, long hszTopic, long hszItem);
long __stdcall DdeQueryNextServer(long hConvList, long hConvPrev);
long __stdcall DdeQueryStringA(long idInst, long hsz, char* psz, long cchMax, long iCodePage);
long __stdcall DdeReconnect(long hConv);
long __stdcall DdeSetUserHandle(long hConv, long id, long hUser);
long __stdcall DdeUnaccessDataA(long hData);
long __stdcall DdeUninitialize(long idInst);
long __stdcall DefDlgProcA(long hDlg, long wMsg, long wParam, long lParam);
long __stdcall DefFrameProcA(long hwnd, long hWndMDIClient, long wMsg, long wParam, long lParam);
long __stdcall DefMDIChildProcA(long hwnd, long wMsg, long wParam, long lParam);
long __stdcall DefWindowProcA(long hwnd, long wMsg, long wParam, long lParam);
long __stdcall DeferWindowPos(long hWinPosInfo, long hwnd, long hWndInsertAfter, long x, long y, long cx, long cy, long wFlags);
long __stdcall DeleteMenu(long hMenu, long nPosition, long wFlags);
long __stdcall DestroyAcceleratorTable(long haccel);
long __stdcall DestroyCaret(void);
long __stdcall DestroyCursor(long hCursor);
long __stdcall DestroyIcon(long hIcon);
long __stdcall DestroyMenu(long hMenu);
long __stdcall DestroyWindow(long hwnd);
long __stdcall DlgDirListA(long hDlg, char* lpPathSpec, long nIDListBox, long nIDStaticPath, long wFileType);
long __stdcall DlgDirListComboBoxA(long hDlg, char* lpPathSpec, long nIDComboBox, long nIDStaticPath, long wFileType);
long __stdcall DlgDirSelectComboBoxExA(long hWndDlg, char* lpszPath, long cbPath, long idComboBox);
long __stdcall DlgDirSelectExA(long hWndDlg, char* lpszPath, long cbPath, long idListBox);
long __stdcall DragObject(long hWnd1, long hWnd2, long un, long dw, long hCursor);
long __stdcall DrawIcon(long hdc, long x, long y, long hIcon);
long __stdcall DrawIconEx(long hdc, long xLeft, long yTop, long hIcon, long cxWidth, long cyWidth, long istepIfAniCur, long hbrFlickerFreeDraw, long diFlags);
long __stdcall DrawMenuBar(long hwnd);
long __stdcall DrawStateA(long hDC, long hBrush, long lpDrawStateProc, long lParam, long wParam, long n1, long n2, long n3, long n4, long un);
long __stdcall EmptyClipboard(void);
long __stdcall EnableMenuItem(long hMenu, long wIDEnableItem, long wEnable);
long __stdcall EnableScrollBar(long hwnd, long wSBflags, long wArrows);
long __stdcall EnableWindow(long hwnd, long fEnable);
long __stdcall EndDeferWindowPos(long hWinPosInfo);
long __stdcall EndDialog(long hDlg, long nResult);
long __stdcall EnumChildWindows(long hWndParent, long lpEnumFunc, long lParam);
long __stdcall EnumClipboardFormats(long wFormat);
long __stdcall EnumDesktopWindows(long hDesktop, long lpfn, long lParam);
long __stdcall EnumDesktopsA(long hwinsta, long lpEnumFunc, long lParam);
long __stdcall EnumPropsA(long hWnd, long lpEnumFunc);
long __stdcall EnumPropsExA(long hWnd, long lpEnumFunc, long lParam);
long __stdcall EnumThreadWindows(long dwThreadId, long lpfn, long lParam);
long __stdcall EnumWindowStationsA(long lpEnumFunc, long lParam);
long __stdcall EnumWindows(long lpEnumFunc, long lParam);
long __stdcall ExcludeUpdateRgn(long hdc, long hwnd);
long __stdcall ExitWindows(long dwReserved, long uReturnCode);
long __stdcall ExitWindowsEx(long uFlags, long dwReserved);
long __stdcall FindWindowA(char* lpClassName, char* lpWindowName);
long __stdcall FindWindowExA(long hWnd1, long hWnd2, char* lpsz1, char* lpsz2);
long __stdcall FlashWindow(long hwnd, long bInvert);
long __stdcall FreeDDElParam(long msg, long lParam);
long __stdcall GetActiveWindow(void);
long __stdcall GetCapture(void);
long __stdcall GetCaretBlinkTime(void);
long __stdcall GetClassLongA(long hwnd, long nIndex);
long __stdcall GetClassNameA(long hwnd, char* lpClassName, long nMaxCount);
long __stdcall GetClassWord(long hwnd, long nIndex);
long __stdcall GetClipboardDataA(long wFormat);
long __stdcall GetClipboardFormatNameA(long wFormat, char* lpString, long nMaxCount);
long __stdcall GetClipboardOwner(void);
long __stdcall GetClipboardViewer(void);
long __stdcall GetCursor(void);
long __stdcall GetDC(long hwnd);
long __stdcall GetDCEx(long hwnd, long hrgnclip, long fdwOptions);
long __stdcall GetDesktopWindow(void);
long __stdcall GetDialogBaseUnits(void);
long __stdcall GetDlgCtrlID(long hwnd);
long __stdcall GetDlgItem(long hDlg, long nIDDlgItem);
long __stdcall GetDlgItemInt(long hDlg, long nIDDlgItem, long lpTranslated, long bSigned);
long __stdcall GetDlgItemTextA(long hDlg, long nIDDlgItem, char* lpString, long nMaxCount);
long __stdcall GetDoubleClickTime(void);
long __stdcall GetFocus(void);
long __stdcall GetForegroundWindow(void);
long __stdcall GetInputState(void);
long __stdcall GetKBCodePage(void);
long __stdcall GetKeyNameTextA(long lParam, char* lpBuffer, long nSize);
long __stdcall GetKeyboardLayout(long dwLayout);
long __stdcall GetKeyboardLayoutList(long nBuff, long* lpList);
long __stdcall GetKeyboardLayoutNameA(char* pwszKLID);
long __stdcall GetKeyboardType(long nTypeFlag);
long __stdcall GetLastActivePopup(long hwndOwnder);
long __stdcall GetMenu(long hwnd);
long __stdcall GetMenuCheckMarkDimensions(void);
long __stdcall GetMenuContextHelpId(long hMenu);
long __stdcall GetMenuDefaultItem(long hMenu, long fByPos, long gmdiFlags);
long __stdcall GetMenuItemCount(long hMenu);
long __stdcall GetMenuItemID(long hMenu, long nPos);
long __stdcall GetMenuState(long hMenu, long wID, long wFlags);
long __stdcall GetMenuStringA(long hMenu, long wIDItem, char* lpString, long nMaxCount, long wFlag);
long __stdcall GetMessageExtraInfo(void);
long __stdcall GetMessagePos(void);
long __stdcall GetMessageTime(void);
long __stdcall GetNextDlgGroupItem(long hDlg, long hCtl, long bPrevious);
long __stdcall GetNextDlgTabItem(long hDlg, long hCtl, long bPrevious);
long __stdcall GetOpenClipboardWindow(void);
long __stdcall GetParent(long hwnd);
long __stdcall GetPriorityClipboardFormat(long* lpPriorityList, long nCount);
long __stdcall GetProcessWindowStation(void);
long __stdcall GetPropA(long hwnd, char* lpString);
long __stdcall GetQueueStatus(long fuFlags);
long __stdcall GetScrollPos(long hwnd, long nBar);
long __stdcall GetScrollRange(long hwnd, long nBar, long* lpMinPos, long* lpMaxPos);
long __stdcall GetSubMenu(long hMenu, long nPos);
long __stdcall GetSysColor(long nIndex);
long __stdcall GetSysColorBrush(long nIndex);
long __stdcall GetSystemMenu(long hwnd, long bRevert);
long __stdcall GetSystemMetrics(long nIndex);
long __stdcall GetTabbedTextExtentA(long hdc, char* lpString, long nCount, long nTabPositions, long* lpnTabStopPositions);
long __stdcall GetThreadDesktop(long dwThread);
long __stdcall GetTopWindow(long hwnd);
long __stdcall GetUpdateRgn(long hwnd, long hRgn, long fErase);
long __stdcall GetWindow(long hwnd, long wFlag);
long __stdcall GetWindowContextHelpId(long hWnd);
long __stdcall GetWindowDC(long hwnd);
long __stdcall GetWindowLongA(long hwnd, long nIndex);
long __stdcall GetWindowRgn(long hWnd, long hRgn);
long __stdcall GetWindowTextA(long hwnd, char* lpString, long cch);
long __stdcall GetWindowTextLengthA(long hwnd);
long __stdcall GetWindowThreadProcessId(long hwnd, long* lpdwProcessId);
long __stdcall GrayStringA(long hDC, long hBrush, long lpOutputFunc, long lpData, long nCount, long X, long Y, long nWidth, long nHeight);
long __stdcall HideCaret(long hwnd);
long __stdcall HiliteMenuItem(long hwnd, long hMenu, long wIDHiliteItem, long wHilite);
long __stdcall ImpersonateDdeClientWindow(long hWndClient, long hWndServer);
long __stdcall InSendMessage(void);
long __stdcall InvalidateRgn(long hwnd, long hRgn, long bErase);
long __stdcall IsChild(long hWndParent, long hwnd);
long __stdcall IsClipboardFormatAvailable(long wFormat);
long __stdcall IsDlgButtonChecked(long hDlg, long nIDButton);
long __stdcall IsIconic(long hwnd);
long __stdcall IsMenu(long hMenu);
long __stdcall IsWindow(long hwnd);
long __stdcall IsWindowEnabled(long hwnd);
long __stdcall IsWindowUnicode(long hwnd);
long __stdcall IsWindowVisible(long hwnd);
long __stdcall IsZoomed(long hwnd);
long __stdcall KillTimer(long hwnd, long nIDEvent);
long __stdcall LoadAcceleratorsA(long hInstance, char* lpTableName);
long __stdcall LoadBitmapA(long hInstance, char* lpBitmapName);
long __stdcall LoadCursorA(long hInstance, char* lpCursorName);
long __stdcall LoadCursorFromFileA(char* lpFileName);
long __stdcall LoadIconA(long hInstance, char* lpIconName);
long __stdcall LoadImageA(long hInst, char* lpsz, long un1, long n1, long n2, long un2);
long __stdcall LoadKeyboardLayoutA(char* pwszKLID, long flags);
long __stdcall LoadMenuA(long hInstance, char* lpString);
long __stdcall LoadMenuIndirectA(long lpMenuTemplate);
long __stdcall LoadStringA(long hInstance, long wID, char* lpBuffer, long nBufferMax);
long __stdcall LockWindowUpdate(long hwndLock);
long __stdcall MapVirtualKeyA(long wCode, long wMapType);
long __stdcall MapVirtualKeyExA(long uCode, long uMapType, long dwhkl);
long __stdcall MessageBeep(long wType);
long __stdcall MessageBoxA(long hwnd, char* lpText, char* lpCaption, long wType);
long __stdcall MessageBoxExA(long hwnd, char* lpText, char* lpCaption, long uType, long wLanguageId);
long __stdcall MoveWindow(long hwnd, long x, long y, long nWidth, long nHeight, long bRepaint);
long __stdcall MsgWaitForMultipleObjects(long nCount, long* pHandles, long fWaitAll, long dwMilliseconds, long dwWakeMask);
long __stdcall OemKeyScan(long wOemChar);
long __stdcall OemToCharA(char* lpszSrc, char* lpszDst);
long __stdcall OemToCharBuffA(char* lpszSrc, char* lpszDst, long cchDstLength);
long __stdcall OpenClipboard(long hwnd);
long __stdcall OpenDesktopA(char* lpszDesktop, long dwFlags, short fInherit, long dwDesiredAccess);
long __stdcall OpenIcon(long hwnd);
long __stdcall OpenInputDesktop(long dwFlags, short fInherit, long dwDesiredAccess);
long __stdcall OpenWindowStationA(char* lpszWinSta, short fInherit, long dwDesiredAccess);
long __stdcall PackDDElParam(long msg, long uiLo, long uiHi);
long __stdcall PaintDesktop(long hdc);
long __stdcall PostMessageA(long hwnd, long wMsg, long wParam, long lParam);
long __stdcall PostThreadMessageA(long idThread, long msg, long wParam, long lParam);
long __stdcall RegisterClipboardFormatA(char* lpString);
long __stdcall RegisterHotKey(long hwnd, long id, long fsModifiers, long vk);
long __stdcall RegisterWindowMessageA(char* lpString);
long __stdcall ReleaseCapture(void);
long __stdcall ReleaseDC(long hwnd, long hdc);
long __stdcall RemoveMenu(long hMenu, long nPosition, long wFlags);
long __stdcall RemovePropA(long hwnd, char* lpString);
long __stdcall ReplyMessage(long lReply);
long __stdcall ReuseDDElParam(long lParam, long msgIn, long msgOut, long uiLo, long uiHi);
long __stdcall SendDlgItemMessageA(long hDlg, long nIDDlgItem, long wMsg, long wParam, long lParam);
long __stdcall SendMessageCallbackA(long hwnd, long msg, long wParam, long lParam, long lpResultCallBack, long dwData);
long __stdcall SendMessageTimeoutA(long hwnd, long msg, long wParam, long lParam, long fuFlags, long uTimeout, long* lpdwResult);
long __stdcall SendNotifyMessageA(long hwnd, long msg, long wParam, long lParam);
long __stdcall SetActiveWindow(long hwnd);
long __stdcall SetCapture(long hwnd);
long __stdcall SetCaretBlinkTime(long wMSeconds);
long __stdcall SetCaretPos(long x, long y);
long __stdcall SetClassLongA(long hwnd, long nIndex, long dwNewLong);
long __stdcall SetClassWord(long hwnd, long nIndex, long wNewWord);
long __stdcall SetClipboardDataA(long wFormat, long hMem);
long __stdcall SetClipboardViewer(long hwnd);
long __stdcall SetCursor(long hCursor);
long __stdcall SetCursorPos(long x, long y);
long __stdcall SetDlgItemInt(long hDlg, long nIDDlgItem, long wValue, long bSigned);
long __stdcall SetDlgItemTextA(long hDlg, long nIDDlgItem, char* lpString);
long __stdcall SetDoubleClickTime(long wCount);
long __stdcall SetFocus(long hwnd);
long __stdcall SetForegroundWindow(long hwnd);
long __stdcall SetMenu(long hwnd, long hMenu);
long __stdcall SetMenuContextHelpId(long hMenu, long dw);
long __stdcall SetMenuDefaultItem(long hMenu, long uItem, long fByPos);
long __stdcall SetMenuItemBitmaps(long hMenu, long nPosition, long wFlags, long hBitmapUnchecked, long hBitmapChecked);
long __stdcall SetMessageExtraInfo(long lParam);
long __stdcall SetMessageQueue(long cMessagesMax);
long __stdcall SetParent(long hWndChild, long hWndNewParent);
long __stdcall SetProcessWindowStation(long hWinSta);
long __stdcall SetPropA(long hwnd, char* lpString, long hData);
long __stdcall SetScrollPos(long hwnd, long nBar, long nPos, long bRedraw);
long __stdcall SetScrollRange(long hwnd, long nBar, long nMinPos, long nMaxPos, long bRedraw);
long __stdcall SetSysColors(long nChanges, long* lpSysColor, long* lpColorValues);
long __stdcall SetSystemCursor(long hcur, long id);
long __stdcall SetThreadDesktop(long hDesktop);
long __stdcall SetTimer(long hWnd, long nIDEvent, long uElapse, long lpTimerFunc);
long __stdcall SetWindowContextHelpId(long hWnd, long dw);
long __stdcall SetWindowLongA(long hwnd, long nIndex, long dwNewLong);
long __stdcall SetWindowPos(long hwnd, long hWndInsertAfter, long x, long y, long cx, long cy, long wFlags);
long __stdcall SetWindowRgn(long hWnd, long hRgn, short bRedraw);
long __stdcall SetWindowTextA(long hwnd, char* lpString);
long __stdcall SetWindowWord(long hwnd, long nIndex, long wNewWord);
long __stdcall SetWindowsHookA(long nFilterType, long pfnFilterProc);
long __stdcall SetWindowsHookExA(long idHook, long lpfn, long hmod, long dwThreadId);
long __stdcall ShowCaret(long hwnd);
long __stdcall ShowCursor(long bShow);
long __stdcall ShowOwnedPopups(long hwnd, long fShow);
long __stdcall ShowScrollBar(long hwnd, long wBar, long bShow);
long __stdcall ShowWindow(long hwnd, long nCmdShow);
long __stdcall ShowWindowAsync(long hWnd, long nCmdShow);
long __stdcall SwapMouseButton(long bSwap);
long __stdcall SwitchDesktop(long hDesktop);
long __stdcall TabbedTextOutA(long hdc, long x, long y, char* lpString, long nCount, long nTabPositions, long* lpnTabStopPositions, long nTabOrigin);
long __stdcall UnhookWindowsHook(long nCode, long pfnFilterProc);
long __stdcall UnhookWindowsHookEx(long hHook);
long __stdcall UnloadKeyboardLayout(long HKL);
long __stdcall UnpackDDElParam(long msg, long lParam, long* puiLo, long* puiHi);
long __stdcall UnregisterClassA(char* lpClassName, long hInstance);
long __stdcall UnregisterHotKey(long hwnd, long id);
long __stdcall UpdateWindow(long hwnd);
long __stdcall ValidateRgn(long hwnd, long hRgn);
long __stdcall WaitForInputIdle(long hProcess, long dwMilliseconds);
long __stdcall WaitMessage(void);
long __stdcall WinHelpA(long hwnd, char* lpHelpFile, long wCommand, long dwData);
long __stdcall WindowFromDC(long hdc);
long __stdcall WindowFromPoint(long xPoint, long yPoint);
short __stdcall DdeInitializeA(long* pidInst, long pfnCallback, long afCmd, long ulRes);
short __stdcall GetAsyncKeyState(long vKey);
short __stdcall GetKeyState(long nVirtKey);
short __stdcall GetWindowWord(long hwnd, long nIndex);
